//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryAjaxInAsp.NETMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class ItemMst
    {
        public int ItemId { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("Name")]
        public string ItemName { get; set; }
        [DisplayName("Description")]
        public string ItemDescription { get; set; }
        [DisplayName("Price")]
        public Nullable<decimal> ItemPrice { get; set; }
        [DisplayName("Image")]
        public string ItemImage { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }

        public ItemMst()
        {
            ItemImage = "~/AppFiles/Images/default.jpg";
        }
    }
}
